### PR TITLE
Add Salsa dip recipe

### PR DESCRIPTION
**Pull request by sexybiggetje**
Add a quick and tasty salsa dip for dipping your veggies or nachos!
Happy dipping :-)

### CODE REVIEW

**Comment by andy5995** [comment]
@sexybiggetje I showed this to my sister, she said she'd rather use fresh tomatoes. I wonder if it would be good to add alternative instructions for making with fresh tomatoes.

**Comment by sexybiggetje** [comment]
Fresh tomatoes contain tomato skin, I don't like that. But canned tomatoes are just that: canned fresh tomatoes. I don't know of other differences and always use canned :-) saves you the trouble of peeling :').

But as for adding an alternative instruction, sure I see no harm in that!

**Comment by sexybiggetje** [comment]
@andy5995 the instructions have changed a little bit per your suggestion :)

**Comment by andy5995** [comment]
@obfuscurity would you be able to review this PR for @hacktoberfest? (@sexybiggetje is a friend of mine)

**Pull request merged**
