### PR TITLE
Generate README.md

### PR DESCRIPTION
**Pull request by Raymonzut**
Elixir gen script for README.md from recipe folders in this repo

NOTE: this branch also contains commits of #10

### CODE REVIEW

**Comment by obfuscurity** [comment]
I appreciate the contribution, but I've never used Elixir. If it's something to adopt here, it might help to add a CONTRIBUTING document or development tips in the README.

**Comment by Raymonzut** [comment]
Yes totally, here is the CONTRIBUTING document.

Feel free to close the PR if it doesn't suit the project, then I will only keep it in the fork.

Thank you for taking a look and already merging #10.

**Comment by obfuscurity** [comment]
Thanks!

**Comment by andy5995** [comment]
@Raymonzut well done!

**Pull request merged**
